services:
  redis-medaid:
    image: redis:latest
    container_name: redis-medaid
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medaid-backend-network
  

  mongo-medaid:
    image: mongo:latest
    container_name: mongo-medaid
    ports:
      - "27020:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=atul1306
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=medaid
    volumes:
      - "mongodb_data:/data/db"
    networks:
      - medaid-backend-network
    
  api-gateway:
    image: api-gateway:v1
    container_name: api-gateway
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - identity-service
      - math-tutor-service
      - redis-medaid
    environment:
      - IDENTITY_SERVICE_URL=http://identity-service:3002
      - MATH_TUTOR_SERVICE_URL=http://math-tutor-service:8000
      - REDIS_URL=redis://redis-medaid:6379
      - ACCESS_TOKEN_SECRET=myaccesstokensecret
    networks:
      - medaid-backend-network


  identity-service:
    image: identity-service:v1
    container_name: identity-service-medaid
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongo-medaid
    environment:
      - MONGODB_URL=mongodb://atul1306:12345@mongo-medaid:27017/medaid?authSource=admin
    networks:
      - medaid-backend-network
    
  math-tutor-service:
    image: math-tutor:v1
    container_name: mathtutor-medaid
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo-medaid
      - redis-medaid
    environment:
      - MONGODB_URL=mongodb://atul1306:12345@mongo-medaid:27017/medaid?authSource=admin
      - REDIS_URL=redis://redis-medaid:6379
      - MONGO_DB_NAME=medaid
    networks:
      - medaid-backend-network
  
networks:
  medaid-backend-network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data:
    